// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: '',
  );
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: '',
  );
  static const String _appleApiKey = String.fromEnvironment(
    'FIREBASE_APPLE_API_KEY',
    defaultValue: '',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:807475730103:web:0c6367e7613e4283ae5f32',
    messagingSenderId: '807475730103',
    projectId: 'flexi-nodes',
    authDomain: 'flexi-nodes.firebaseapp.com',
    storageBucket: 'flexi-nodes.firebasestorage.app',
    measurementId: 'G-V06FPKTNKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:807475730103:android:df07fbc584d91045ae5f32',
    messagingSenderId: '807475730103',
    projectId: 'flexi-nodes',
    storageBucket: 'flexi-nodes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _appleApiKey,
    appId: '1:807475730103:ios:bd7a29048c930b6bae5f32',
    messagingSenderId: '807475730103',
    projectId: 'flexi-nodes',
    storageBucket: 'flexi-nodes.firebasestorage.app',
    iosBundleId: 'com.example.flexiNode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _appleApiKey,
    appId: '1:807475730103:ios:bd7a29048c930b6bae5f32',
    messagingSenderId: '807475730103',
    projectId: 'flexi-nodes',
    storageBucket: 'flexi-nodes.firebasestorage.app',
    iosBundleId: 'com.example.flexiNode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:807475730103:web:5cfe2bceeeb809adae5f32',
    messagingSenderId: '807475730103',
    projectId: 'flexi-nodes',
    authDomain: 'flexi-nodes.firebaseapp.com',
    storageBucket: 'flexi-nodes.firebasestorage.app',
    measurementId: 'G-TF21KQYC6T',
  );
}
